add z-index 9999 to query suggestion popup (#11651)
* add z-index 9999 to query suggestion popup

This is an attempt to "fix" the cypress test which is actually a
false positive alarm

The cypress test shows:
```
         should show and select suggestions progressively:
     AssertionError: Timed out retrying after 15000ms: expected '<div.editor-widget.suggest-widget.with-status-bar.visible.shows-details>' to be 'visible'

This element `<div.editor-widget.suggest-widget.with-status-bar.visible.shows-details>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:
```

But the fixed element is NOT covered by the button which has z-index: 1000

Signed-off-by: Yulong Ruan <ruanyl@amazon.com>

* Changeset file for PR #11651 created/updated

---------

Signed-off-by: Yulong Ruan <ruanyl@amazon.com>
Co-authored-by: opensearch-changeset-bot[bot] <154024398+opensearch-changeset-bot[bot]@users.noreply.github.com>